# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Studio C
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Studio C is a client-based web design company established in 2009 located at
  Southwest Career and Technical Academy in Las Vegas, Nevada. As a company run
  by students, we handle business in a professional and expedient manner. Our
  experienced and skilled members will develop original, appealing, and
  high-quality websites that will suit client’s needs in all non-profit
  and business endeavors.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Studio-C-2017

# Build settings
markdown: kramdown

collections:
    works:
        output: true

defaults:
    -
        scope:
            path: ""
            type: works
        values:
            layout: work
